name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: Test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-15-intel # TODO: KyleMayes/install-llvm-action doesn't have support for Aarch64
            clang: ["10.0", "clang_10_0"]
            rust: "1.60.0"
          - name: Ubuntu
            os: ubuntu-latest
            clang: ["10.0", "clang_10_0"]
            rust: "1.60.0" # MSRV
          - name: Windows
            os: windows-latest
            clang: ["10.0", "clang_10_0"]
            rust: "1.60.0" # MSRV

    steps:
      - uses: actions/checkout@v6

      # LLVM and Clang
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}
          key: ${{ matrix.os }}-llvm-${{ matrix.clang[0] }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.clang[0] }}
          directory: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      # Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      # Test
      - name: Cargo Test (Dynamic)
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}/lib
          LLVM_CONFIG_PATH: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}/bin/llvm-config
        run: cargo test --verbose --features ${{ matrix.clang[1] }} -- --nocapture

      - name: Cargo Test (Runtime)
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}/lib
          LLVM_CONFIG_PATH: ${{ runner.temp }}/llvm-${{ matrix.clang[0] }}/bin/llvm-config
        run: cargo test --verbose --features "${{ matrix.clang[1] }} runtime" -- --nocapture
